# PostgreSQL reactive config
quarkus.datasource.db-kind=postgresql

quarkus.datasource.username=postgres
quarkus.datasource.password=L@n151005

quarkus.datasource.reactive.url=postgresql://localhost:5432/chatify

quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true